### PR TITLE
Suppport Python 3.12

### PR DESCRIPTION
**Pull request by alecandido**

### CODE REVIEW

**Comment by alecandido** [comment]
Just waiting for https://github.com/qiboteam/qibo/pull/1231 to be merged

**Review by yjmaxpayne — CHANGES_REQUESTED** [review]
Thanks Alessandro for the implementation. I noticed all tests are passing, but the test for python 3.12 is not included. You may wish to change the corresponding workflow in `deploy.yml`: `python-version: [3.9, "3.10", "3.11"]` to include 3.12.

**Comment by yjmaxpayne** [comment]
> > Thanks Alessandro for the implementation. I noticed all tests are passing, but the test for python 3.12 is not included. You may wish to change the corresponding workflow in `deploy.yml`: `python-version: [3.9, "3.10", "3.11"]` to include 3.12.
> 
> Done, thanks @yjmaxpayne
> 
> EDIT: of course it was done in [3718d5c](https://github.com/qiboteam/qibotn/commit/3718d5c8bca63f63bfd42234a2679adf9776951e), _after_ this comment (because I didn't notice the push didn't go through...)

Got a runtime error on dependencies for the python 3.12 test. 

```bash
RuntimeError

  Unable to find installation candidates for kahypar (1.3.5)

  at ~/.local/venv/lib/python3.12/site-packages/poetry/installation/chooser.py:74 in choose_for
       [70](https://github.com/qiboteam/qibotn/actions/runs/8703157064/job/23868729420?pr=48#step:9:71)│ 
       71│             links.append(link)
       [72](https://github.com/qiboteam/qibotn/actions/runs/8703157064/job/23868729420?pr=48#step:9:73)│ 
       73│         if not links:
    →  74│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       [75](https://github.com/qiboteam/qibotn/actions/runs/8703157064/job/23868729420?pr=48#step:9:76)│ 
       76│         # Get the best link
       77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       [78](https://github.com/qiboteam/qibotn/actions/runs/8703157064/job/23868729420?pr=48#step:9:79)│ 

Cannot install kahypar.

Error: Process completed with exit code 1.
```

**Comment by alecandido** [comment]
Yes, I saw it:

https://github.com/qiboteam/qibotn/actions/runs/8703157064/job/23868729420#step:9:65

**Comment by alecandido** [comment]
Sorry for the late reply: unfortunately, there is nothing we can do in QiboTN to fix the former error.

`kahypar` never released support for py3.12 https://pypi.org/project/kahypar/#files (no wheel for py3.12, and no source on PyPI).

So, either we can remove that dependency from Poetry
https://github.com/qiboteam/qibotn/blob/3718d5c8bca63f63bfd42234a2679adf9776951e/pyproject.toml#L42-L43
or we have to wait for them.

However, the dependency is only required for the docs, and it is only making the build failing.
In principle, we could even remove `docs` from here:
https://github.com/qiboteam/qibotn/blob/ae3163e292429f2e8cde6f07355f85913b2fc9a2/.github/workflows/deploy.yml#L21
and neglect the problem.

**Comment by Vinitha-balachandran** [comment]
> Sorry for the late reply: unfortunately, there is nothing we can do in QiboTN to fix the former error.
> 
> `kahypar` never released support for py3.12 https://pypi.org/project/kahypar/#files (no wheel for py3.12, and no source on PyPI).
> 
> So, either we can remove that dependency from Poetry
> 
> https://github.com/qiboteam/qibotn/blob/3718d5c8bca63f63bfd42234a2679adf9776951e/pyproject.toml#L42-L43
> 
> 
> or we have to wait for them.
> However, the dependency is only required for the docs, and it is only making the build failing. In principle, we could even remove `docs` from here:
> 
> https://github.com/qiboteam/qibotn/blob/ae3163e292429f2e8cde6f07355f85913b2fc9a2/.github/workflows/deploy.yml#L21
> 
> 
> and neglect the problem (but, if we don't fix it, it will make the publishing workflow failing afterward).

Hi Alessandro, I find the lines 42-43 introduced to avoid quimb warning in pyproject.toml file not working (even for the released version). Liwei also finds same problem.  This is the warning ".conda/envs/qibotn_new/lib/python3.12/site-packages/cotengra/hyperoptimizers/hyper.py:33: UserWarning: Couldn't import `kahypar` - skipping from default hyper optimizer and using basic `labels` method instead.". So, I think we may remove the lines 42-43. Other than this warning, the tests will pass.
    warnings.warn(

**Comment by alecandido** [comment]
> Hi Alessandro, I find the lines 42-43 introduced to avoid quimb warning in pyproject.toml file not working (even for the released version). Liwei also finds same problem. This is the warning:

This is definitely expected, since those lines are meant to be evaluated in the CI, but it won't happen in other scenarios, especially for the released version, that fully lost track of the Poetry settings (since only actual dependencies are propagated to the wheels).

If you want to make use of them, you should install with `poetry install --with docs` (given the group where they are located), or move them up to the actual dependencies (but I would avoid, since we don't strictly need it).

If the goal was to save the warning to the QiboTN user, that was not an appropriate solution, so I agree we should drop them. If instead there was a reason to prevent the warning during docs generation, it should be reassessed the original motivation.

**Review by BrunoLiegiBastonLiegi — APPROVED** [review]
Thanks, looks good. Just out of curiosity, how did you handle the issue of `kahypar` not having wheels for 3.12 in the end?

**Comment by alecandido** [comment]
> Thanks, looks good. Just out of curiosity, how did you handle the issue of `kahypar` not having wheels for 3.12 in the end?

Removing the dependency on `kahypar`, that was just saving a warning in the docs generation. We now have the warning back, but Poetry is able to resolve dependencies for py3.12.

**Pull request merged**
